### ISSUE TITLE
Does VLG-Net try to do experiments on charades-sta?

### ISSUE THREAD

**Issue by onlyonewater** [Soldelli/VLG-Net#6]
and I want to use VLG-Net for my own dataset, How to use it? And how can I get depencendy_matrices in annotations?

**Comment by onlyonewater** [comment]
@Soldelli

**Comment by Soldelli** [comment]
Hi @onlyonewater thank you for reaching out. 
We did some limited experimentation with Charades-STA, however, we made the decision to not promote this dataset due to some limitations. Kindly refer to the supplementary material of the paper for additional explanations. 

Please check [this](https://github.com/Soldelli/VLG-Net/issues/3#issuecomment-1219774599) thread for information on how to compute the dependency_matrices. 

Kindly let me know if I can help you further. 

Best, 
Mattia

**Comment by onlyonewater** [comment]
ok, thanks!!! now I know how to compute dependency matrices, I have another question, do you have charades-sta annotation files (json version)?

**Comment by Soldelli** [comment]
You can use the files attached to this message. 
They contain the same information as the original Charadest STA annotations, which come in csv format.
[charades_sta_annotations.zip](https://github.com/Soldelli/VLG-Net/files/9868967/charades_sta_annotations.zip)

**Comment by onlyonewater** [comment]
ok, thanks!!! I got it.

**Comment by onlyonewater** [comment]
for the tacos and activitynet dataset, How many GPUs are you using for the default configuration?

**Comment by Soldelli** [comment]
I believe all experiments are run on a single GPU. Back then it was probably a v100.

**Comment by onlyonewater** [comment]
ok, thanks!!
