### ISSUE TITLE
doc/environment.md问题

### ISSUE THREAD

**Issue by c1d2y3** [Soldelli/VLG-Net#9]
你好，我安照conda env create -f environment.yml去配置环境，报各种的错误，然后用doc/environment.md去配置报错，
脚本试图使用YACS库中的merge_from_list函数从通过命令行参数提供的列表中合并配置选项。
然而，错误发生在YACS库的第243行，其中它检查配置字典中是否存在特定的键（python）。断言失败，表示配置中不存在python键。

Traceback (most recent call last):
  File "E:/SF4/VLG-Net-master/train_net.py", line 277, in <module>
    main()
  File "E:/SF4/VLG-Net-master/train_net.py", line 226, in main
    cfg.merge_from_list(args.opts)
  File "D:\ProgramData\Anaconda3\envs\net\lib\site-packages\yacs\config.py", line 243, in merge_from_list
    _assert_with_logging(subkey in d, "Non-existent key: {}".format(full_key))
  File "D:\ProgramData\Anaconda3\envs\net\lib\site-packages\yacs\config.py", line 525, in _assert_with_logging
    assert cond, msg
AssertionError: Non-existent key: python
如何修改

**Comment by Soldelli** [comment]
Dear @c1d2y3 i am unsure of the root cause of this error. 
I suspect that the structure of the data folder was not respected and therefore the config files are not properly loaded. 
Kindly make sure you are following the data folder structure or you provide the correct paths to the config files. 

I hope this helps you.

**Comment by c1d2y3** [comment]
我用的是win10，就是需要设置num-worker=0，跑起来时间长，也出现了loss=nan问题，怎么解决？

**Comment by Soldelli** [comment]
Dear @c1d2y3 are you respecting the default hyperparameters used to train this network? Particularly in TACoS, it seems to cause NaNs when the batch size is reduced. 
No solution has been investigated/reported since the repository was released.
